import Head from "next/head";
import Image from "next/image";
import Jokes from "../src/components/jokes/Jokes";
import styles from "../styles/Home.module.css";

export default function Home({ page }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jokes</h1>
        <Jokes page={page} />
      </main>

      <footer className={styles.footer}>
        <a
          href="http://icanhazdadjoke.com"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.footerLink}
        >
          Random dad jokes thanks to
          <span className={styles.logo}>
            <Image
              src="/smile.svg"
              alt="icanhazdadjoke logo"
              width={28}
              height={28}
            />
          </span>
          icanhazdadjoke.com
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  let { page } = context.query;

  return {
    props: {
      page: page ? parseInt(page, 10) : 1,
    },
  };
}
