import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://icanhazdadjoke.com"
          target="_blank"
          rel="noopener noreferrer"
          className={styles.footerLink}
        >
          Random dad jokes thanks to
          <span className={styles.logo}>
            <Image
              src="/smile.svg"
              alt="icanhazdadjoke logo"
              width={28}
              height={28}
            />
          </span>
          icanhazdadjoke.com
        </a>
      </footer>
    </div>
  );
}
